# Dùng image Python 3.10
FROM python:3.10-slim

WORKDIR /app

COPY streamlit-requirements.txt .
RUN pip install --no-cache-dir -r streamlit-requirements.txt

COPY ./streamlit .

EXPOSE 8501

HEALTHCHECK CMD curl -f http://localhost:8501/_stcore/health

ENTRYPOINT ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]